### ISSUE TITLE
Pack Tactics on the wiki

### ISSUE THREAD

**Issue by MotoMoto1234** [thatlonelybugbear/FoundryMacros#3]
**Describe the bug**
Update the pack tactics in the wiki to include an rwak as well for kobolds.  They have ranged attacks and get advantage if an ally is within range using the same feature.  

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thatlonelybugbear** [comment]
Changed to all attacks instead of only `mwak`
