### ISSUE TITLE
Wiki change

### ISSUE THREAD

**Issue by MotoMoto1234** [thatlonelybugbear/FoundryMacros#4]
Replace discord link for the Overtime Cheat sheet with either my wiki link or you can literally copy my page into your wiki:

https://github.com/MotoMoto1234/Midi-Wiki/wiki/Overtime-Cheat-Sheet

This way its not launching an external link to a discord app.  

My item checklist in my wiki is going to be a long project don't bother linking it yet.

**Comment by thatlonelybugbear** [comment]
Done thanks!
