### ISSUE TITLE
Update ***The List***

### ISSUE THREAD

**Issue by MotoMoto1234** [thatlonelybugbear/FoundryMacros#6]
In the wiki, add "Obsidian" to the list of modules that don't work with midiqol.  Its basically same as Ready Set Roll.

**Comment by thatlonelybugbear** [comment]
Added <https://github.com/thatlonelybugbear/FoundryMacros/wiki/MidiQOL-knowledge-database-by-@MotoMoto1234#midi-does-not-work-with>
